# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('murano', '0002_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_role',
            old_name='ip',
            new_name='role',
        ),
    ]
